#!/bin/bash
for i in $(seq $1 $2)
do	       
    curl  "http://54.147.228.251:3019/buil/$i" -o "zona-$i-buildings.osm"
    curl  "http://54.147.228.251:3019/addr/$i" -o "zona-$i-addresses.osm"
done


